theme="material-design"
themesDir = "themes"
baseurl = "https://example.org/"
languageCode = "en-us"
title = "caldo.io"
MetaDataFormat = "toml"
paginate = 9 # To specify a multiple of 3
disqusShortname = "disqus_vyXr0nndHv" # optional
copyright = "© 2017 Copyright - Alain Gonzalez"

[params]
  name = "Alain"
  description = "The Sauce for Today's Enterprise IS Management" # optional
  bio = "I make enterprise digital transformation happen"
  twitter = "@gonzalezalain" # optional
  # gitlab = "Your Gitlab Name" # optional
  github = "alainglez" # optional
  # facebook = "Your facebook Name" # optional
  # gplus = "Your Google+ profile name" # optional
  linkedin = "alain.gonzalez@gmail.com" # optional
  headerCover = "images/default.png" # "images/headerCover.png" # optional
  footerCover = "images/default.png" # optional
  googleAnalyticsUserID = "Your Analytics User Id" # optional

[permalinks]
  post = "/:year/:month/:day/:title/" # optional
